### ISSUE TITLE
Won't install on XCode 7.1

### ISSUE THREAD

**Issue by PaulSlocum** [kitschpatrol/KPRunEverywhereXcodePlugin#11] opened 2015-10-30 05:45 UTC
It worked on beta 7.1, but when I installed the official 7.1 (7B91b) it no longer shows up in the menus.  Reinstalling didn't help.

**Comment by kitschpatrol** [comment] 2015-10-30 15:33
Paul, thanks for writing. I can't reproduce this. I tried uninstalling / reinstalling on 7B91b and the plugin is still showing up just fine:

<img width="445" alt="screen shot 2015-10-30 at 11 00 32 am" src="https://cloud.githubusercontent.com/assets/194164/10849147/a36501f4-7ef5-11e5-84fe-760249dd71bc.png">

Couple things to try... can you please confirm that you have the latest binary:
`shasum ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/KPRunEverywhereXcodePlugin.xcplugin/Contents/MacOS/KPRunEverywhereXcodePlugin`

Should yield 64a2c64fa5caf38b9cdf5691c4cffb4e357d46fc.

Have you tried:
`defaults read com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1`

If you don't see com.kitschpatrol.KPRunEverywhereXcodePlugin in the allowed list, please run

`defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1`

Then restart Xcode and be sure to click "Load Bundles" when prompted.

Let me know if this helps.

**Comment by kitschpatrol** [comment] 2015-11-16 01:59
Closing this since I can't reproduce and I've been using the plugin on 7.1 without incident.  Please re-open if the above didn't help and you're still having trouble. Thanks.

**Closed by kitschpatrol** 2015-11-16 01:59 UTC
